[package]
name = "market-finance"
version = "0.1.0"
authors = ["Fred Briden <fred.briden@gmail.com>"]
license = "MIT"
description = "A collection of utilities for the financial markets."
keywords = [ "finance", "stocks" ]
readme = "README.md"
edition = "2018"

[dependencies]
